[systemS]
system = "x86_64-linux"
hostName = "mehran-beast"
stateVersion = "25.05"
machine = "AMD"
packages= [
  "neofetch",
  "vim",
  "wget",
  "unzip",
  "kitty",
  "starship",
  "fishPlugins.done",
  "fishPlugins.fzf-fish",
  "fishPlugins.forgit",
  "fishPlugins.nvm",
  "ffmpeg",
  "fzf",
  "libva",
  "libva-vdpau-driver",
  "libva-utils",
  "fishPlugins.grc",
  "grc",
  "openssl",
  "home-manager",
  "pipewire",
  "wireplumber",
  "cachix",
  "python3Minimal"
  ]
[userS]
user = "mehran"
name = "Mehran Shahidi"
userIcon = "assets/mehran.png"
email = "m.mehrashahidi@gmail.com"
nixDir = "/home/mehran/.nixconf"
wm = "hyprland"
font = "Intel One Mono"
fontPkg = "intel-one-mono"
editor = "nvim"
packages = [
  "brave",
  "google-chrome",
  "vlc",
  "obsidian",
  "telegram-desktop",
  "discord",
  "thunderbird",
  "spotify",
  "calibre",
  "zotero",
  "xournalpp",
  "yazi",
  "gimp3-with-plugins",

  "lazygit",
  "lazydocker",
  "android-tools",
  "tlaplusToolbox",
  "tlaplus",

  "glab",
  "rustc",
  "cargo",
  "exercism",
  "go",
  "gcc",
  "nodejs",
  "jq",

# Local cert
  "mkcert",
  "nssTools",

  "imv",
  "qimgv",
  "watson",
  "networkmanagerapplet",
  "brightnessctl",
  "libnotify",
  "wireguard-tools",
  "wlr-randr",
  "atool",
  "httpie",
  "lazygit",
  "lazydocker",
  "android-tools",
  "jmtpfs",
  "scrcpy",
  "emote",
  "presenterm",
  "chezmoi",
  "fd",
  "bat",
  "showmethekey",
  "audacity",
  "nix-du",
  "trash-cli",
  "vulkan-tools",
  "unrar",
  "vectorcode",
]

[ubuntu]
user = "mehranshahidi"
name = "Mehran Shahidi"
email = "mehran.shahidi@checkmk.com"
nixDir = "/home/mehranshahidi/Projects/nixos-conf"
font = "Intel One Mono"
fontPkg = "intel-one-mono"
editor = "nvim"
packages = [
  "lazygit",
  "lazydocker",
  "neofetch",

  "glab",
  "rustc",
  "cargo",
  "exercism",
  "go",
  "gcc",
  "nodejs",
  "nodePackages.pnpm",
  "nodePackages.typescript",
  "python3",
  "python3Packages.pip",
  "jq",
  "nssTools",

  "fzf",
  "wireguard-tools",
  "atool",
  "grpcurl",
  "httpie",
  "lazygit",
  "grc",
  "lazydocker",
  "fd",
  "bat",
]

