[opener]
zathura = [{ run = 'zathura "$@"', orphan = true, desc = "Open with Zathura" }]
# image viewer
imv = [{ run = 'imv "$@" .', desc = "Open with imv" }]
qimgv = [{ run = 'qimgv -- "$@"', desc = "Open with qimgv" }]

mpvvr = [{ run = 'mpv  --vf=lavfi=[crop=iw/2:ih:0:0,lenscorrection=cx=0.5:cy=0.5:k1=-0.3:k2=-0.3] --vo=gpu-next --gpu-context=wayland hwdec=nvdec "$@"', orphan = true, desc = "VR mpv" }]

bino = [{ run = 'bino "$@"', orphan = true, desc = "Open with bino" }]

extract = [
	{ run = 'ya pub extract --list "$@"', desc = "Extract here", for = "unix" },
  ]



[open]
rules = [
    { mime = "application/pdf", use = ["zathura", "open"] },
    # Folder
    { name = "*/", use = [ "edit", "open", "reveal" ] },
    # Text
    { mime = "text/*", use = [ "edit", "reveal" ] },
    # Image
    { mime = "image/*", use = [ "imv", "qimgv", "open", "reveal" ] },
    # Media
    { mime = "{audio,video}/*", use = [ "play", "mpvvr", "bino", "reveal" ] },
    # Archive
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "reveal" ] },
    # JSON
    { mime = "application/{json,ndjson}", use = [ "edit", "reveal" ] },
    { mime = "*/javascript", use = [ "edit", "reveal" ] },
    # Empty file
    { mime = "inode/empty", use = [ "edit", "reveal" ] },
    # Fallback
    { name = "*", use = [ "open", "reveal" ] },
]
