# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usbhid"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f1c0483e-9ff0-4a29-a408-60cd93e7955e";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/14E2-DB63";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/mnt/windows" = {
    device = "/dev/disk/by-uuid/02E89952E89944B7"; # Replace with your partition ID
    fsType = "ntfs"; # Use "ntfs3" or "ntfs-3g" if needed
    options = [
      "uid=1000" # your user id (id -u)
      "gid=100" # usually the 'users' group (id -g)
      "umask=022" # rwx for owner, rx for group/others
      "windows_names" # forbid characters illegal on Windows
      # "ro"            # uncomment for read-only
      # "ignore_case"   # if you want case-insensitive lookups
    ];
  };

  swapDevices = [
    {
      device = "/var/lib/swapfile";
      size = 16 * 1024;
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-46571b93cde7.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-79bcf4840eaf.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-8885f6af0d56.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-b7736139a81e.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-d26f8f350c48.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.vboxnet0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
